cat <<EOF >$OE_CONFIG
[options]
addons_path = $OE_SUPERADMIN
admin_passwd = $OE_SUPERADMIN
csv_internal_sep = ,
data_dir = $OE_WORKSPACE
db_host = $OE_DB_HOST
db_maxconn = $OE_DB_MAXCONN
db_name = False
db_password = $OE_DB_PASSWORD
db_port = $OE_DB_PORT
db_sslmode = prefer
db_template = template0
db_user = $OE_DB_USER
dbfilter = 
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface = 
http_port = $OE_PORT
import_partial = 
limit_memory_hard = $OE_HARD_MEMORY
limit_memory_soft = $OE_SOFT_MEMORY
limit_request = $OE_REQUEST
limit_time_cpu = 90
limit_time_real = 180
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = $OE_LOG_PATH/odoo-server.log
longpolling_port = $OE_LONGPOLL_PORT
max_cron_threads = 1
osv_memory_age_limit = False
osv_memory_count_limit = False
pg_path = 
pidfile = 
proxy_mode = False
reportgz = False
screencasts = 
screenshots = /tmp/odoo_tests
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file = 
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path = 
without_demo = False
workers = $OE_WORKERS
xmlrpc = True
xmlrpc_interface = 127.0.0.1
xmlrpc_port = $OE_PORT
netrpc = True
netrpc_interface = 127.0.0.1
netrpc_port = $OE_NETRPC_PORT

EOF